version: "3"

services:

  shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb-data:/data/db"
    ports:
      - "27017:27017"

volumes:
  mongodb-data: